name: Build and Test on diverse OS

on: workflow_dispatch 

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    # continue-on-error: false
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build Test Docs
      continue-on-error: true
      run: |

        pip install --upgrade pip wheel build
        python -m build
        pip install .[tests]

        python -c 'import pyquickbench' 

        pytest

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os  }}-${{ matrix.python-version }}
        path: './dist/'

  gather-dists:
    runs-on: ubuntu-latest
    needs: build
    env:
      python-version-source: "ubuntu-latest-3.11"
    if: success() || failure()
    steps:

      - name: Download reports' artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts-dl

      - name: Copy artifacts
        run: |
          mkdir pyquickbench-dist
          mkdir pyquickbench-dist/dist
          find ./artifacts-dl/${{ env.python-version-source }}/ -name '*.tar.gz' -exec cp {} ./pyquickbench-dist/dist \; 
          find ./artifacts-dl -name '*.whl' -exec cp {} ./pyquickbench-dist/dist \; 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyquickbench-dist
          path: './pyquickbench-dist/'
